name: Auto Live from Codex
on:
  push:
    branches: [codex-work]

permissions:
  contents: write

jobs:
  merge_to_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fast-forward main to codex-work
        run: |
          git config user.name "auto-live-bot"
          git config user.email "auto-live-bot@users.noreply.github.com"
          git fetch origin
          git checkout main
          git merge --ff-only origin/codex-work
          git push origin main
