name: Bunny Ops
on:
  workflow_dispatch:
    inputs:
      task:
        description: "Bash to run"
        required: true
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write
  workflows: write

jobs:
  comment:
    if: github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/bunny ')
    runs-on: ubuntu-latest
    steps:
      - name: Extract task
        id: x
        run: |
          body="${{ github.event.comment.body }}"
          echo "task=${body#'/bunny '}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BUNNY_PAT }}
      - name: Run
        env:
          GH_TOKEN: ${{ secrets.BUNNY_PAT }}
        run: |
          set -e
          bash -lc "${{ steps.x.outputs.task }}"

  manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BUNNY_PAT }}
      - name: Run
        env:
          GH_TOKEN: ${{ secrets.BUNNY_PAT }}
        run: |
          set -e
          bash -lc "${{ inputs.task }}"
