name: Prod Rollout

on:
  workflow_dispatch:
    inputs:
      confirm_prod:
        description: "Type YES to proceed"
        required: true
        default: "NO"

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Validate
        run: |
          if [ "${{ github.event.inputs.confirm_prod }}" != "YES" ]; then
            echo "Need YES"
            exit 1
          fi
          echo "Baseline OK"
